services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
